version: '3.8'
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: none

  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432 # Expose port 5432 to localhost:5432 (can use with pgAdmin locally)

  redis:
    image: "redis:alpine"

  client:
    image: peerprep-client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: 
      - nginx
    environment:
      # Add any development build env here
      - BACKEND_URL:localhost
    ports: 
      - 3000:3000
    networks:
      - default
    volumes: 
      - client_node_modules:/app/node_modules
      - ./frontend:/app

  account:
    image: peerprep-account
    build:
      context: ./backend/account
      dockerfile: ../Dockerfile
    depends_on: 
      - postgres
      - nginx
    env_file:
      - ./backend/account/.env
    environment: 
      # App variables
      - CLIENT_URL=http://localhost:3000
      - PORT=8081
      # Database Configuration
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DB_SYNCHRONIZE=true
      # JWT Configuration
      - JWT_ACCESS_TOKEN_SECRET=accSecret
      - JWT_REFRESH_TOKEN_SECRET=refSecret
      - JWT_MAIL_VERIFY_SECRET=mailSecret
      - JWT_PASSWORD_RESET_SECRET=pwSecret
    ports: 
      - 8081:8081
    networks:
      - default
    volumes: 
      - account_node_modules:/app/node_modules
      - ./backend/account:/app

  chat:
    image: peerprep-chat
    build:
      context: ./backend/chat
      dockerfile: ../Dockerfile
    environment: 
      - PORT=8082
    ports: 
      - 8082:8082
    networks:
      - default
    volumes: 
      - chat_node_modules:/app/node_modules
      - ./backend/chat:/app

  interview:
    image: peerprep-interview
    build:
      context: ./backend/interview
      dockerfile: ../Dockerfile
    environment: 
      - PORT=8083
    ports: 
      - 8083:8083
    networks:
      - default
    volumes: 
      - interview_node_modules:/app/node_modules
      - ./backend/interview:/app

  match:
    image: peerprep-match
    build:
      context: ./backend/match
      dockerfile: ../Dockerfile
    depends_on: 
      - nginx
    environment: 
      - PORT=8084
    ports: 
      - 8084:8084
    networks:
      - default
    volumes: 
      - match_node_modules:/app/node_modules
      - ./backend/match:/app

volumes: 
  postgres:
  match_node_modules:
  interview_node_modules:
  chat_node_modules:
  account_node_modules:
  client_node_modules:

networks:
  default:
    name: peerprep-development
    driver: bridge