version: '3.8'
services:  

  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres:/var/lib/postgresql/data
    ports: 
      - 5432:5432

  client:
    image: peerprep-client:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    # env_file:
    #   # Use .env file to handle secret env variables
    #   - frontend/.env
    environment:
      # Add any development build env here
      - BACKEND_URL:localhost
    ports: 
      - 8080:80

  account:
    image: peerprep-account:prod
    build:
      context: ./backend/account
      dockerfile: ../Dockerfile.production
    depends_on: 
      - postgres
    environment: 
      - PORT=8081
    ports: 
      - 8081:8081

  chat:
    image: peerprep-chat:prod
    build:
      context: ./backend/chat
      dockerfile: ../Dockerfile.production
    environment: 
      - PORT=8082
    ports: 
      - 8082:8082

  interview:
    image: peerprep-interview:prod
    build:
      context: ./backend/interview
      dockerfile: ../Dockerfile.production
    environment: 
      - PORT=8083
    ports: 
      - 8083:8083

  match:
    image: peerprep-match:prod
    build:
      context: ./backend/match
      dockerfile: ../Dockerfile.production
    environment: 
      - PORT=8084
    ports: 
      - 8084:8084

volumes: 
  postgres:

networks:
  default:
    name: peerprep-production
