apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: 656831507331.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep-account
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: awscred
