apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match
          image: 656831507331.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep-match
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-config
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
      imagePullSecrets:
        - name: awscred
