# Sample environment config
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: peerprep
data:
  CLIENT_URL: https://peer-prep.live
  DATABASE_URL: postgresql://[user[:password]@][netloc][:port][/dbname]
  DB_SYNCHRONIZE: "false"
  JWT_ACCESS_TOKEN_SECRET: accessSecret
  JWT_REFRESH_TOKEN_SECRET: refreshSecret
  JWT_MAIL_VERIFY_SECRET: mailSecret
  JWT_PASSWORD_RESET_SECRET: resetSecret
  REDIS_HOST: redis # or aws elasticache redis endpoint
  REDIS_PORT: "6379"
  EMAIL_ID: "[username]@gmail.com"
  EMAIL_PASS: "[password]"