apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: peerprep
  annotations:
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-path: /interview
spec:
  selector:
    app: interview
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
