apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: peerprep
  annotations:
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-path: /match
spec:
  selector:
    app: match
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
