apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: account-hpa
  namespace: peerprep
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account
  targetCPUUtilizationPercentage: 75
