name: Build and Push Frontend Client to S3
on:
  # push:
  #   branches:
  #   - '*'
  pull_request:
    types: [closed]

env:
  AWS_DEFAULT_REGION: ap-southeast-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-push:
    name: Build and deploy Frontend Client to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key:${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:$AWS_ACCESS_KEY_ID
          aws-secret-access-key:$AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_DEFAULT_REGION
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn
      - name: Build
        working-directory: ./frontend
        run: yarn build
      - name: Deploy
        working-directory: ./frontend
        run: aws s3 sync build/ s3://peerprep
    # Add additional steps here like scanning of image
